version: '3'

services:
  pdf-converter:
    build: .
    image: pdf-raster-ocr
    volumes:
      - ./sample:/input
      - pdf_output:/output
    depends_on:
      - postgres
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=flipbook
      - PGPORT=5432

  api-server:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - pdf_output:/output
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=flipbook
      - PGPORT=5432
      - PORT=3000

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flipbook
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  postgres-data:
  pdf_output:
