# Use Node.js 18 as the base image
FROM node:18-slim

# Install PostgreSQL client
RUN apt-get update && apt-get install -y libpq-dev

# Set the working directory
WORKDIR /app

# Copy package files
COPY apps/api/package*.json ./

# Install dependencies
RUN npm install
RUN npm install -g nodemon

# Expose API port
EXPOSE 3000

# Set the entrypoint with live reload
CMD ["nodemon", "--watch", "/app/src", "--ext", "mjs,js,json", "src/api-server.mjs"] 